version: '3'
services:
  redis:
    image: 'redis:latest'
    ports:
      - '6333:6379'
    volumes:
      - ./data:/data
  bookstoreapi:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - redis
