###
POST http://localhost:3000/signup
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjE0IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY1NTk5NDQ5NSwiZXhwIjoxNjU1OTk0NTI1fQ.JaWFdLbNo9DGXycktvCSjSpsL8PpXqos8AITKcDvv5U
Content-Type: application/json

{   
    "username": "user44",
    "email":"test@gmail.com",
    "pwd": "test"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{   
    "username": "user44",
    "email":"test@gmail.com",
    "pwd": "test"
}

###
POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXI0NCIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE2NTYwMDcwMjN9.CRzQfNjzddyEL88hk-flVPYjB7JA9MIyCagGKAVpguQ"
}

###
DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXI0NCIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE2NTYwMDcwMjN9.CRzQfNjzddyEL88hk-flVPYjB7JA9MIyCagGKAVpguQ"
}


###

GET http://localhost:3000/

###
GET http://localhost:3000/users/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjE0IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY1NTk5NDQ5NSwiZXhwIjoxNjU1OTk0NTI1fQ.JaWFdLbNo9DGXycktvCSjSpsL8PpXqos8AITKcDvv5U

###
GET http://localhost:3000/users/1/novels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjE0IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY1NTk5NDQ5NSwiZXhwIjoxNjU1OTk0NTI1fQ.JaWFdLbNo9DGXycktvCSjSpsL8PpXqos8AITKcDvv5U

###
PUT http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjE0IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY1NTk5NDQ5NSwiZXhwIjoxNjU1OTk0NTI1fQ.JaWFdLbNo9DGXycktvCSjSpsL8PpXqos8AITKcDvv5U
Content-Type: application/json

{   
    "bio":"hiii"
}

###
GET http://localhost:3000/novels/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjE0IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY1NTk5NDQ5NSwiZXhwIjoxNjU1OTk0NTI1fQ.JaWFdLbNo9DGXycktvCSjSpsL8PpXqos8AITKcDvv5U

###
GET http://localhost:3000/novels/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjE0IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY1NTk5NDQ5NSwiZXhwIjoxNjU1OTk0NTI1fQ.JaWFdLbNo9DGXycktvCSjSpsL8PpXqos8AITKcDvv5U

###
POST http://localhost:3000/novels/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoidXNlcjQ0IiwiaWF0IjoxNjU2MDExMjk2LCJleHAiOjE2NTYwMTMwOTZ9.0JN14BVJA5PkQCTWIQ2-7-XFYO6CzzCRQa_y7a4_JIE
Content-Type: application/json

{   
    "title": "from rest test",
    "summary":"nice one really"
}

###
PUT http://localhost:3000/novels/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlcjE0IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY1NTk5NDQ5NSwiZXhwIjoxNjU1OTk0NTI1fQ.JaWFdLbNo9DGXycktvCSjSpsL8PpXqos8AITKcDvv5U
Content-Type: application/json

{   
    "user_id": 1,
    "title": "from rest test",
    "summary":"nice one really"
}