name: Build and push Docker image upon release

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: bookstoreapi
      DOCKER_REGISTRY: rabbitbeta
      COMMIT_BRANCH: ${GITHUB_REF#refs/heads/}
      COMMIT_SHA: $(git rev-parse --short "$GITHUB_SHA")
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Create API env
        run: |
          touch .env
          echo "postgresql://${{secrets.PG_USER}}:${{secrets.PG_PWD}}@${{secrets.PG_HOST}}:${{secrets.PG_PORT}}/${{secrets.PG_DB}}"
          echo "PORT"=${{ secrets.PORT}}  >> .env
          echo "PG_USER"=${{ secrets.PG_USER}}  >> .env
          echo "PG_HOST"=${{secrets.PG_HOST}}  >> .env
          echo "PG_DB"=${{secrets.PG_DB}}  >> .env
          echo "PG_PWD"=${{secrets.PG_PWD}}  >> .env
          echo "PG_PORT"=${{secrets.PG_PORT}}  >> .env
          echo "ACCESS_TOKEN_SECRET"=${{secrets.ACCESS_TOKEN_SECRET}}  >> .env
          echo "REFRESH_TOKEN_SECRET"=${{secrets.REFRESH_TOKEN_SECRET}}  >> .env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Create image
        run: |
          echo "$IMAGE_NAME"
          echo "${{ env.DOCKER_REGISTRY}}/${{ env.IMAGE_NAME}}:v_${{ env.COMMIT_BRANCH}}-${{ env.COMMIT_SHA}}"
          docker-compose build $IMAGE_NAME
          docker tag "${{IMAGE_NAME}}:latest" ${{ env.DOCKER_REGISTRY}}/${{ env.IMAGE_NAME}}:v_${{ env.COMMIT_BRANCH}}-${{ env.COMMIT_SHA}}
          docker push "${{ env.DOCKER_REGISTRY}}/${{ env.IMAGE_NAME}}:v_${{ env.COMMIT_BRANCH}}-${{ env.COMMIT_SHA}}"
