name: Build and push Docker image upon release

on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: bookstoreapi
  DOCKER_REGISTRY: rabbitbeta
  COMMIT_SHA: $(git rev-parse --short "$GITHUB_SHA")

jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Create API env
        run: |
          touch .env
          echo "postgresql://${{secrets.PG_USER}}:${{secrets.PG_PWD}}@${{secrets.PG_HOST}}:${{secrets.PG_PORT}}/${{secrets.PG_DB}}"
          echo "PORT"=${{ secrets.PORT}}  >> .env
          echo "PG_USER"=${{ secrets.PG_USER}}  >> .env
          echo "PG_HOST"=${{secrets.PG_HOST}}  >> .env
          echo "PG_DB"=${{secrets.PG_DB}}  >> .env
          echo "PG_PWD"=${{secrets.PG_PWD}}  >> .env
          echo "PG_PORT"=${{secrets.PG_PORT}}  >> .env
          echo "ACCESS_TOKEN_SECRET"=${{secrets.ACCESS_TOKEN_SECRET}}  >> .env
          echo "REFRESH_TOKEN_SECRET"=${{secrets.REFRESH_TOKEN_SECRET}}  >> .env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Create image
        run: |
          echo "$GITHUB_REF"
          echo "$COMMIT_BRANCH"
          echo "$COMMIT_SHA"
          export COMMIT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          docker-compose build $IMAGE_NAME
          docker tag "$DOCKER_REGISTRY/$IMAGE_NAME:latest" "$DOCKER_REGISTRY/$IMAGE_NAME:latest"
          docker push "$DOCKER_REGISTRY/$IMAGE_NAME:latest"
          docker tag "$IMAGE_NAME:latest" "$DOCKER_REGISTRY/$IMAGE_NAME:v_$GITHUB_REF_NAME-$COMMIT_SHA"
          docker push "$DOCKER_REGISTRY/$IMAGE_NAME:v_$GITHUB_REF_NAME-$COMMIT_SHA"
