name: Build and push Docker image upon release

on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Create API env
        run: |
          touch .env
          echo "postgresql://${{secrets.PG_USER}}:${{secrets.PG_PWD}}@${{secrets.PG_HOST}}:${{secrets.PG_PORT}}/${{secrets.PG_DB}}"
          echo "PORT"=${{ secrets.PORT}}  >> .env
          echo "PG_USER"=${{ secrets.PG_USER}}  >> .env
          echo "PG_HOST"=${{secrets.PG_HOST}}  >> .env
          echo "PG_DB"=${{secrets.PG_DB}}  >> .env
          echo "PG_PWD"=${{secrets.PG_PWD}}  >> .env
          echo "PG_PORT"=${{secrets.PG_PORT}}  >> .env
          echo "ACCESS_TOKEN_SECRET"=${{secrets.ACCESS_TOKEN_SECRET}}  >> .env
          echo "REFRESH_TOKEN_SECRET"=${{secrets.REFRESH_TOKEN_SECRET}}  >> .env

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1 # Info: https://github.com/docker/build-push-action/tree/releases/v2#tags
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
          tag_with_ref: true # Info: https://github.com/docker/build-push-action/tree/releases/v1#tag_with_ref
          tag_with_sha: true # Info: https://github.com/docker/build-push-action/tree/releases/v1#tag_with_sha
          tags: latest
